"""sync schema

Revision ID: ad4c625e8b9e
Revises: 2b9ef4e555f9
Create Date: 2026-04-01 01:44:52.095495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad4c625e8b9e'
down_revision: Union[str, None] = '2b9ef4e555f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tenants', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_column('user_tenants', 'role_override')
    op.drop_column('user_tenants', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tenants', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_tenants', sa.Column('role_override', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_tenants', 'id')
    # ### end Alembic commands ###
