"""expand core data model

Revision ID: f2756728038b
Revises: c5268b144015
Create Date: 2026-03-10 15:56:43.159639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2756728038b'
down_revision: Union[str, None] = 'c5268b144015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor_trades',
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('contractor_id', 'trade_id')
    )
    op.add_column('contractors', sa.Column('legal_name', sa.String(length=255), nullable=True))
    op.add_column('contractors', sa.Column('dba_name', sa.String(length=255), nullable=True))
    op.add_column('contractors', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('contractors', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('contractors', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('contractors', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('contractors', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('contractors', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.add_column('contractors', sa.Column('county', sa.String(length=100), nullable=True))
    op.add_column('contractors', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('contractors', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('contractors', sa.Column('service_radius', sa.Integer(), nullable=True))
    op.add_column('contractors', sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('enrichment_jobs', sa.Column('entity_type', sa.String(length=50), nullable=False))
    op.add_column('enrichment_jobs', sa.Column('entity_id', sa.Integer(), nullable=False))
    op.add_column('enrichment_jobs', sa.Column('payload', sa.JSON(), nullable=True))
    op.add_column('enrichment_jobs', sa.Column('result', sa.JSON(), nullable=True))
    op.drop_constraint('enrichment_jobs_lead_id_fkey', 'enrichment_jobs', type_='foreignkey')
    op.drop_column('enrichment_jobs', 'lead_id')
    op.add_column('leads', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('leads', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.add_column('leads', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('licenses', sa.Column('license_type', sa.String(length=100), nullable=True))
    op.add_column('licenses', sa.Column('classification', sa.String(length=100), nullable=True))
    op.add_column('licenses', sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('licenses', sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('licenses', sa.Column('bond_amount', sa.Integer(), nullable=True))
    op.add_column('licenses', sa.Column('workers_comp_status', sa.String(length=50), nullable=True))
    op.add_column('licenses', sa.Column('workers_comp_expiration', sa.DateTime(timezone=True), nullable=True))
    op.add_column('licenses', sa.Column('primary_license', sa.Boolean(), nullable=True))
    op.add_column('zipcodes', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('zipcodes', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('zipcodes', sa.Column('timezone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zipcodes', 'timezone')
    op.drop_column('zipcodes', 'longitude')
    op.drop_column('zipcodes', 'latitude')
    op.drop_column('licenses', 'primary_license')
    op.drop_column('licenses', 'workers_comp_expiration')
    op.drop_column('licenses', 'workers_comp_status')
    op.drop_column('licenses', 'bond_amount')
    op.drop_column('licenses', 'expiration_date')
    op.drop_column('licenses', 'issue_date')
    op.drop_column('licenses', 'classification')
    op.drop_column('licenses', 'license_type')
    op.drop_column('leads', 'longitude')
    op.drop_column('leads', 'latitude')
    op.drop_column('leads', 'postal_code')
    op.drop_column('leads', 'state')
    op.drop_column('leads', 'city')
    op.drop_column('leads', 'address_line2')
    op.drop_column('leads', 'address_line1')
    op.add_column('enrichment_jobs', sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('enrichment_jobs_lead_id_fkey', 'enrichment_jobs', 'leads', ['lead_id'], ['id'])
    op.drop_column('enrichment_jobs', 'result')
    op.drop_column('enrichment_jobs', 'payload')
    op.drop_column('enrichment_jobs', 'entity_id')
    op.drop_column('enrichment_jobs', 'entity_type')
    op.drop_column('contractors', 'last_enriched_at')
    op.drop_column('contractors', 'service_radius')
    op.drop_column('contractors', 'longitude')
    op.drop_column('contractors', 'latitude')
    op.drop_column('contractors', 'county')
    op.drop_column('contractors', 'postal_code')
    op.drop_column('contractors', 'state')
    op.drop_column('contractors', 'city')
    op.drop_column('contractors', 'address_line2')
    op.drop_column('contractors', 'address_line1')
    op.drop_column('contractors', 'entity_type')
    op.drop_column('contractors', 'dba_name')
    op.drop_column('contractors', 'legal_name')
    op.drop_table('contractor_trades')
    # ### end Alembic commands ###
